### ISSUE TITLE
Error while importing test module in HARK

### ISSUE THREAD

**Issue by sytoraman** [ccarrollATjhuecon/Methods#27]
**I run a test to check whether everything works in HARK, but I came across with an error. The screenshot of the error message can be seen below:**

<img width="681" alt="Error_methods" src="https://user-images.githubusercontent.com/56057085/93689547-97188f00-fa9d-11ea-9c91-08e79b72d560.png">

**Comment by ccarrollATjhuecon** [comment]
@MridulS,

I have reproduced this same error on my Econ-ARK machine.  Seems to be something wrong with the requirements.txt file -- I guess we need to add interpolation.py as one of the requirements.   - From @llorracc

**Comment by MridulS** [comment]
interpolation.py is already part of the requirements.txt file.

How is the master branch installed ?

**Comment by llorracc** [comment]
@MridulS, thanks for helping me diagnose and fix the problem.

For everyone else: The problem was that when the HARK repo was installed as part of the creation of the Econ-ARK machine, 
via the 

git clone https://github.com/econ-ark/HARK

command, what is obtained is the latest "master" branch of HARK at the time when the installer script gets run.  This is basically the "development" branch, and therefore can contain stuff that is not contained in the most recent "release."  The "released" version is installed elsewhere, via the command "pip install --upgrade econ-ark" and that command installed the requirements for that version of the toolkit.  

Any further requirements needed to be satisfied by the command:
gi bran
